[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "termcolours"
dynamic = ["version"]
description = "Interactive terminal color picker"
readme = "README.md"
requires-python = ">=3.9"
license = { text = "MIT" }
authors = [{ name = "pykhaz" }]

dependencies = ["pyperclip"]

[tool.hatch.version]
path = "src/termcolours/__about__.py"

[project.scripts]
termcolours = "termcolours.cli:main"

[tool.hatch.envs.test]
dependencies = ["pytest"]
develop = true

[tool.hatch.envs.test.scripts]
test = "pytest -v"
