[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "termcolors"
dynamic = ["version"]
description = "Interactive terminal color picker"
readme = "README.md"
requires-python = ">=3.9"
license = { text = "MIT" }
authors = [{ name = "pykhaz" }]

dependencies = ["pyperclip"]

[tool.hatch.version]
path = "src/termcolors/__about__.py"

[project.scripts]
termcolors = "termcolors.cli:main"
